# services.yaml
create_reservation:
  fields:
    entry_id:
      selector:
        config_entry:
          integration: dvsportal
    entity_id:
      selector:
        entity:
          filter:
            - integration: dvsportal
              domain: sensor
              device_class: dvs_car_sensor
    license_plate_value:
      example: "ABC123"
      selector:
        text: null
    license_plate_name:
      example: "My Car"
      selector:
        text: null
    date_from:
      example: "2023-10-10T18:29:00"
      selector:
        datetime: null
    date_until:
      example: "2023-10-10T20:29:00"
      selector:
        datetime: null

end_reservation:
  fields:
    entity_id:
      selector:
        entity:
          filter:
            - integration: dvsportal
              domain: sensor
              device_class: dvs_car_sensor
          multiple: false
